[package]
name = "lalrpop-example"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = { version = "0.22.1", features = [
    "lexer",
    "unicode",
] }

[build-dependencies]
lalrpop = "0.22.1"

